//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XamarinWebSite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAR
    {
        public int CARID { get; set; }
        public string BRAND { get; set; }
        public string MODEL { get; set; }
        public string YEAR { get; set; }
        public string IMAGE { get; set; }
        public byte[] DETAILS { get; set; }
    }
}
