//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XamarinWebSite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class USER
    {
        public int USERID { get; set; }
        public string NAME { get; set; }
        public string SURNAME { get; set; }
        public string PASSWORD { get; set; }
        public string USERNAME { get; set; }
    }
}
